# Generated by Django 6.0.5 on 2026-05-28 17:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(default='📦', help_text='Эмодзи-иконка категории', max_length=10)),
                ('color', models.CharField(default='#ffd700', help_text='HEX-цвет категории, например #ffd700', max_length=7)),
            ],
            options={
                'verbose_name': 'категория бюджета',
                'verbose_name_plural': 'категории бюджета',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Максимальный лимит расходов за месяц', max_digits=12)),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Уже потрачено в этом месяце', max_digits=12)),
                ('month', models.PositiveSmallIntegerField(help_text='Месяц (1–12)')),
                ('year', models.PositiveSmallIntegerField(help_text='Год, например 2025')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='budget.budgetcategory')),
            ],
            options={
                'verbose_name': 'бюджет',
                'verbose_name_plural': 'бюджеты',
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'category', 'month', 'year')},
            },
        ),
    ]
