# Generated by Django 6.0.5 on 2026-06-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_budget_created_at_budget_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
