# Generated by Django 6.0.5 on 2026-06-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_budget_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='slug',
            field=models.SlugField(default='', editable=False, unique=True),
        ),
    ]
