# Generated by Django 6.0.5 on 2026-05-28 17:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('target_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Целевая сумма накопления', max_digits=12)),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Уже накоплено', max_digits=12)),
                ('deadline', models.DateField(blank=True, help_text='Дата достижения цели', null=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='🎯', help_text='Эмодзи-иконка цели', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'цель',
                'verbose_name_plural': 'цели',
                'ordering': ['-created_at'],
            },
        ),
    ]
