# Generated by Django 6.0.5 on 2026-05-28 17:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0002_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Годовая процентная ставка, %', max_digits=5)),
                ('term_months', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Активен'), ('closed', 'Закрыт')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='banking.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'депозит',
                'verbose_name_plural': 'депозиты',
                'ordering': ['-created_at'],
            },
        ),
    ]
