# Generated by Django 6.0.5 on 2026-06-03 12:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_deleted_at_user_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('level', models.CharField(choices=[('bronze', 'Бронза'), ('silver', 'Серебро'), ('gold', 'Золото'), ('platinum', 'Платина')], default='bronze', max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('score_details', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'финансовый рейтинг',
                'verbose_name_plural': 'финансовые рейтинги',
            },
        ),
    ]
