# Generated by Django 6.0.5 on 2026-05-26 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(editable=False, max_length=16, unique=True)),
                ('cvv', models.CharField(editable=False, max_length=3)),
                ('expiry_date', models.DateField()),
                ('is_frozen', models.BooleanField(default=False)),
                ('card_type', models.CharField(choices=[('virtual', 'Виртуальная')], default='virtual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='banking.account')),
            ],
            options={
                'verbose_name': 'карта',
                'verbose_name_plural': 'карты',
                'ordering': ['-created_at'],
            },
        ),
    ]
