# Generated by Django 6.0.5 on 2026-06-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
