# Generated by Django 6.0.5 on 2026-06-03 08:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_account_deleted_at_account_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_transfer_limit', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=12, verbose_name='Дневной лимит переводов')),
                ('monthly_transfer_limit', models.DecimalField(decimal_places=2, default=Decimal('1000000.00'), max_digits=12, verbose_name='Месячный лимит переводов')),
                ('min_transfer_amount', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, verbose_name='Минимальная сумма перевода')),
                ('max_transfer_amount', models.DecimalField(decimal_places=2, default=Decimal('500000.00'), max_digits=12, verbose_name='Максимальная сумма перевода')),
                ('saving_account_interest_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='Процентная ставка сберегательных счетов (%)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'настройки банка',
                'verbose_name_plural': 'настройки банка',
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('TJS', 'TJS'), ('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB')], default='TJS', max_length=3),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(choices=[('TJS', 'TJS'), ('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB')], max_length=3)),
                ('target_currency', models.CharField(choices=[('TJS', 'TJS'), ('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB')], max_length=3)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'курс валют',
                'verbose_name_plural': 'курсы валют',
                'unique_together': {('base_currency', 'target_currency')},
            },
        ),
    ]
