# Generated by Django 6.0.5 on 2026-06-03 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_banksettings_alter_account_currency_exchangerate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['-updated_at'], 'verbose_name': 'курс валют', 'verbose_name_plural': 'курсы валют'},
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together=set(),
        ),
    ]
