# Generated by Django 6.0.5 on 2026-06-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_alter_exchangerate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('TJS', 'TJS'), ('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('GBP', 'GBP'), ('CNY', 'CNY'), ('JPY', 'JPY'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('TRY', 'TRY'), ('BRL', 'BRL'), ('INR', 'INR'), ('KRW', 'KRW')], default='TJS', max_length=3),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='base_currency',
            field=models.CharField(choices=[('TJS', 'TJS'), ('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('GBP', 'GBP'), ('CNY', 'CNY'), ('JPY', 'JPY'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('TRY', 'TRY'), ('BRL', 'BRL'), ('INR', 'INR'), ('KRW', 'KRW')], max_length=3),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='target_currency',
            field=models.CharField(choices=[('TJS', 'TJS'), ('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('GBP', 'GBP'), ('CNY', 'CNY'), ('JPY', 'JPY'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('TRY', 'TRY'), ('BRL', 'BRL'), ('INR', 'INR'), ('KRW', 'KRW')], max_length=3),
        ),
    ]
