# Generated by Django 6.0.5 on 2026-05-26 12:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0002_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('transaction_type', models.CharField(choices=[('transfer', 'Перевод'), ('payment', 'Платёж'), ('deposit', 'Пополнение'), ('withdrawal', 'Снятие')], max_length=20)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('completed', 'Выполнена'), ('failed', 'Ошибка'), ('cancelled', 'Отменена')], default='pending', max_length=20)),
                ('receiver_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transactions', to='banking.account')),
                ('sender_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_transactions', to='banking.account')),
            ],
            options={
                'verbose_name': 'транзакция',
                'verbose_name_plural': 'транзакции',
                'ordering': ['-created_at'],
            },
        ),
    ]
