# Generated by Django 6.0.5 on 2026-05-31 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шаблона')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('service_provider', models.CharField(max_length=100, verbose_name='Провайдер')),
                ('requisite', models.CharField(max_length=50, verbose_name='Реквизит')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'шаблон платежа',
                'verbose_name_plural': 'шаблоны платежей',
                'ordering': ['-created_at'],
            },
        ),
    ]
