# Generated by Django 6.0.5 on 2026-05-27 02:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('term_months', models.PositiveIntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Годовая процентная ставка, %', max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрен'), ('rejected', 'Отклонён'), ('active', 'Активен'), ('closed', 'Закрыт')], default='pending', max_length=20)),
                ('monthly_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager_comment', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'кредит',
                'verbose_name_plural': 'кредиты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan')),
            ],
            options={
                'verbose_name': 'платёж по кредиту',
                'verbose_name_plural': 'платежи по кредиту',
                'ordering': ['due_date'],
            },
        ),
    ]
