# Generated by Django 6.0.5 on 2026-06-01 04:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpayment',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Штраф за просрочку', max_digits=12),
        ),
    ]
