# Generated by Django 6.0.5 on 2026-06-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanpayment_is_overdue_loanpayment_penalty_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='credit_score',
            field=models.PositiveIntegerField(blank=True, help_text='Кредитный рейтинг клиента (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='credit_score_explanation',
            field=models.TextField(blank=True, help_text='Объяснение кредитного рейтинга от ИИ'),
        ),
    ]
