# Generated by Django 6.0.5 on 2026-06-02 21:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_credit_score_loan_credit_score_explanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название программы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=12, verbose_name='Минимальная сумма')),
                ('max_amount', models.DecimalField(decimal_places=2, default=Decimal('1000000.00'), max_digits=12, verbose_name='Максимальная сумма')),
                ('min_term', models.PositiveIntegerField(default=3, verbose_name='Минимальный срок (месяцев)')),
                ('max_term', models.PositiveIntegerField(default=60, verbose_name='Максимальный срок (месяцев)')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='Процентная ставка (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'кредитная программа',
                'verbose_name_plural': 'кредитные программы',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Кредитная программа', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='loans.loanprogram'),
        ),
    ]
